---
driver:
  name: docker

driver_config:
  foward: 8080

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: tomcat6
    run_list:
      - recipe[jetbrains_license_server::default]
    attributes:
      tomcat:
        base_version: 6
  - name: tomcat7
    run_list:
      - recipe[jetbrains_license_server::default]
    attributes:
      tomcat:
        base_version: 7
  - name: tomcat8
    run_list:
      - recipe[jetbrains_license_server::default]
    attributes:
      tomcat:
        base_version: 8
